### ISSUE TITLE
Does not update

### ISSUE THREAD

**Issue by scarstens** [limetech/dockerapp-plex#1]
this dockers install file does not keep up to date for plexpass members. its way behind, I've had to stop using it... :(

**Comment by limetech** [comment]
In short, there are alternative containers available right now for Plex (not from Lime Tech) that offer ways to use Plex Pass.  The docker install is current for non-Plex Pass members I believe.  In the future, we plan to add Plex Pass support into either this container or another container variant, but not in the short-term.

**Comment by barrystaes** [comment]
I take it this has been fixed? I have a Plex Pass and i use this container.
If not, what exactly are the negative side effects? I did notice it remembers what i've seen, but it cant play the next episode of a series.

And just to be sure;
- So to run the latest Plex version, i just have to (using the Unraid Dynamix web interface) let it update the docker, and it restarts? 
- So Plex automagically upgrades its files (those outside of docker but mounted) where needed?
- So if Plex would release a new "major" version with breaking changes, this would be end up in a separate docker?

There [is](http://lime-technology.com/forum/index.php?topic=26149.0) information on the Unraid related forums, but quite dispersed/old/contradicting.

**Comment by jonpanozzo** [comment]
Our container uses the latest publicly available version of Plex at this time.  Occasionally in the past there have been releases where the Plex Pass users got the release ahead of normal Plex users.  We do not support Plex-Pass only releases at this time.

If Plex reports an update available in its own UI, updating it there is not recommended.  The recommendation is to wait for us to update the container itself and push that release out on our web interface.
