### ISSUE TITLE
Plex not updating... again

### ISSUE THREAD

**Issue by aenglish86** [limetech/dockerapp-plex#12]
Plex is not updating via the unRAID docker. Update has been out for a bit now. Any help is appreciated.

Thanks :)

Details:
Current update version: 1.12.0.4829
Version on docker: 1.11.3.4803

**Comment by eschultz** [comment]
@aenglish86 Just pushed the latest Plex version (1.12.0.4829), try 'check for updates' again in the unRAID web gui

**Comment by kcwebby** [comment]
Looks like a repeat of the issue a month ago.   This docker is several versions behind.    Should we not be using this one?

**Comment by aenglish86** [comment]
I’ve abandoned this repository. Only reason I used it was because it was LimeTech approved. I’ve switched to binhex. Updates are available same day they are released, support is damn near instant. Hope this helps

**Comment by aenglish86** [comment]
@kcwebby add his repository to your docker:

https://github.com/binhex/docker-templates

Stop your current version of plex, and backup your config folder (/mnt/user/appdata/Plex) but don’t delete the docker yet. Download Plex from binhex, stop it as well, then copy over your config data from your old plex docker and then fire up the new docker to make sure it all works before ditching the outdated repository. You cannot run both versions of plex at the same time as they run on the same port, unless you change default ports which I don’t suggest doing if you plan on using plex outside of the house. Hope this helps!
