### ISSUE TITLE
updates are so far behind its stupid now

### ISSUE THREAD

**Issue by aenglish86** [limetech/dockerapp-plex#13]
if nobody is going to keep up with updates which include security patches, then why even have this repository on here. either take it down or keep up with it.

**Comment by eschultz** [comment]
Normally people complain about Plex being out of date with this container which is not the case for the last 19 days.  Thought you switched over to binhex version anyways?

Regardless, I'll update the base image from `phusion/baseimage:0.9.22` to `phusion/baseimage:0.10.1` to address your immediate security updates concerns.

**Comment by aenglish86** [comment]
Why not just pull the image of you only update it when people complain? Seems like a waste of time on everyone’s part
