### ISSUE TITLE
Update plex version

### ISSUE THREAD

**Issue by skylord123** [limetech/dockerapp-plex#17]
1.16.0.1226 is released. I would like to try it to see if it fixes some issues I am having with memory leaks.

**Comment by skylord123** [comment]
Is there any way we can change how updates are handled? It can take quite a while before this container gets updated for new versions.

- Find someone that can help keep this updated 
- Make manual upgrading from Plex UI work
- Allow placing a .deb file or the like in a specific folder and when the docker container starts it will use this version to install

I had a similar issue with a container for running Xeoma and I ended up advising the container dev to have a config file that is generated on start that you put the URL to the .deb file to download and install. If the file is already downloaded it wont fetch it but if it isn't downloaded it will download the URL and install it. This way I could run any version I wanted without dealing with the container dev and was just a simple restart to get the changes (especially if I needed to revert to a previous version).

And FYI I just got an email stating this:

> We're making major changes to how guide data is curated and delivered in Plex. Beginning on June 30, 2019 Plex will require Plex Media Server version **1.16.1** to maintain EPG data and overall Live TV & DVR functionality. **Users that don't upgrade by the above date will begin losing guide data starting July 1, 2019.**

**Comment by eschultz** [comment]
We'll want users of this container to migrate to Plex's official Docker container at some point.  Some testing will be needed to ensure the Plex library still works during the migration.

In the short term though, I'll update this container to 1.16.0.1226... and then 1.16.1 once it's available

**Comment by skylord123** [comment]
@eschultz I wouldn't mind testing the move to the official docker container. Should I just copy my Plex data directory and try the official on that? Have you looked into it to see if there is anything more complicated than that? (if not I can do it no problem)

**Comment by eschultz** [comment]
Please give that a shot.  It _should_ be that easy

**Comment by eschultz** [comment]
FYI, I updated this container to 1.16.0.1226

**Comment by skylord123** [comment]
@eschultz Thanks! 

I just tried the switch to the official docker image and everything went flawlessly.

The mappings for the new virtual folders:
- `/config` stays the same, carry it over from this container.
- `/media` becomes `/data` and because of this I set both of them to my media directory (I launched with just `/data` mapped to my media and I had a bunch of files missing so make sure to map /media so that doesn't happen OR update Plex to point to the new folder, I just thought that was risky)
- There is a new `/transcode` path that I wasn't using before. I just created another folder under my plex config directory called transcode and set it to that (since it is running off my SSD). I believe this was an option in this container I just never used it (which is probably why I had my docker image filling up).

If you are using unraid you can just install the official from Community Applications from user plexinc. I changed the name of the template to PlexMediaServer-Official just so I could tell the two apart. I am keeping this container in my docker instance just disabled for startup JIC I do run into any issues.

I'm pretty happy with how easy it was. I hope this helps others :)

Going to close this now that the update has been applied.

**Comment by eschultz** [comment]
@skylord123 Thanks for trying out the plexinc container, it's much appreciated!  I believe their container will update correctly when you chose to upgrade from plex's web UI -- hopefully you'll get to try this out soon when they release 1.16.1 soon.

Are you using the DVR functionality by chance?

**Comment by skylord123** [comment]
@eschultz Yes. I am using DVR with over the air free broadcasts and using Plex's built in Comskip.

I have been having issues with Comskip getting stuck on shows and then continually eating memory. I'm hoping this latest version fixes my issue. I posted about it on the forums: https://forums.plex.tv/t/memory-leak-since-1-15-x-on-300-plex-server-instances/397403/56?u=skylord123

I'll keep you updated on how things go with upgrades on the official container.

**Comment by skylord123** [comment]
Still having shows getting stuck consuming memory with Comskip on the latest version. Had a show at 3:00 AM this morning that is stuck processing.
