### ISSUE TITLE
Update plexmediaserver_1.18.0.1913-e5cc93306

### ISSUE THREAD

**Issue by crimsdings** [limetech/dockerapp-plex#21]

**Comment by crimsdings** [comment]
uh this was 4 days ago ? can we upgrade please ?

**Comment by crimsdings** [comment]
is this a dead project ? i thought installed the limetech because i thought its the _official_ package of unraid but it seems unsupported?

**Comment by eschultz** [comment]
sorry for the delay.  Upgraded to 1.18.0.1944 now 🍻
