### ISSUE TITLE
Missing latest Plex Media Server Update

### ISSUE THREAD

**Issue by Cwis3man** [limetech/dockerapp-plex#3]
Any ETA on this?

**Comment by eschultz** [comment]
I've submitted the new Dockerfile to Docker Hub so the new release should be available in under an hour.

**Comment by Cwis3man** [comment]
Eric,

I hate to be a pain, but there's a new update out due to broken secure
connections from the last update.

Do you have an ETA on when that will be done?

Secure outside connections are broken until it gets updated.

Thanks for all your help!

**Comment by eschultz** [comment]
Thanks for heads up, I'll be able to get a new release out in a few hours.

I usually check Plex's download achieve daily and they must have just
allowed non-plex-pass users to access their latest version.

**Comment by Cwis3man** [comment]
No problem.

I'm not even sure if this update will fix my issue, but I saw one post
saying that it did.

Here's hoping! Thanks for all your help!

**Comment by eschultz** [comment]
Plex should be up-to-date now, just update the Docker container in unRAID and you should be good (hopefully)

**Comment by Cwis3man** [comment]
Thanks for the quick update, it didn't resolve my issue however. I think
the issue is with TLS, as of 3/31 plex stopped supporting TLS 1.0, so I'm
thinking that is the issue. Not sure how to get around that just yet, as my
server is using openssl 1.0.1s, I'm going to try the 6.2 beta over the
weekend to see if that helps.
