### ISSUE TITLE
not updating?

### ISSUE THREAD

**Issue by wesj830** [limetech/dockerapp-plex#4]
When I look at the WEBUI for plex is says needs to be updated.  When I open unraid and check to see if it need to be updated it says "up-to-date"

This is from PLEX WEBUI

> > > > > > > > Version 0.9.16.6 An update is available. Please install manually. <<<<<<

This is from unraid 
PlexMediaServer     limetech/plex:latest        up-to-date

**Comment by eschultz** [comment]
Please try this: 
On the unRAID web UI go to the Docker page. Toggle on Advanced view (near the top right of the page) and click the 'force update' link for Plex.

**Comment by wesj830** [comment]
WOW Thanks!!!  Worked like a champ!!!
