### ISSUE TITLE
Update Issues

### ISSUE THREAD

**Issue by andrewchumchal** [limetech/dockerapp-plex#5]
Hello Limetech. I have install on my unRAID 6 server. Plex says i need a update but it cannot be OTA it needs to be downloaded and install.  I have read that if you turn off and on a docker. It will update. I have done it many times. Still no success

**Comment by eschultz** [comment]
Please try this:
Docker tab —> toggle on Advanced View (near top right) —> click the ‘force update’ link for PlexMediaServer.

**Comment by andrewchumchal** [comment]
I just saw issues #4 and I do not see a force update button

**Comment by andrewchumchal** [comment]
NVM just found it. Thanks eshultz. Quick question. If i have a plex pass do i get the beta updates ?

**Comment by eschultz** [comment]
Unfortunately we don’t support Plex Pass right now.

**Comment by andrewchumchal** [comment]
Okay thanks. Do you known if you guys would in the near time ?
