### ISSUE TITLE
Not Updating

### ISSUE THREAD

**Issue by jason-bean** [limetech/dockerapp-plex#8]
Not sure why this isn't updating to 1.3.3.3148-b38628e that came out on the December 15th.

**Comment by eschultz** [comment]
I just released the Plex 1.3.3.3148 update to Docker.  Should be available to update the next time you 'Check for Updates' on the unRAID Docker page.

**Comment by avluis** [comment]
Is this not a self-updating container? Or is this a manual process for a reason?
I'll go ahead and request an update to the Dockerfile whenever possible while I'm here~

**Comment by ashleyconnor** [comment]
You can always ssh into the container with `docker exec -i -t {docker_container_id} /bin/bash` and run `bash /install.sh`

Get the container `id` with `docker ps`.

**Comment by eschultz** [comment]
It's not self-updating.  I just upgraded this Docker container to Plex 1.4.3.3433.

We plan to move to Plex's official Docker container at some point (which does auto-update correctly).  The hold-up is seeing if anything breaks during a migration from our Docker container to theirs in the config path...

**Comment by avluis** [comment]
@eschultz So far, I have moved my config folder from this one to Plex and then to linuxserver.io and back around and have yet to have any path issues.

Only thing I would be looking at/paying close attention to would be permissions.
