### ISSUE TITLE
Deluge: Unable to send Torrent

### ISSUE THREAD

**Issue by scbuckeye75** [limetech/dockerapp-plex#9]
Not able to send torrents to deluge.  I have tried to set this manually.  This is using the docker app in Unraid v6.3.5

Please see below for example from the log.  I am able to test the connection to deluge webui successfully, however.

2017-07-06 23:18:06 WARNING SEARCHQUEUE-MANUAL-161511 :: Deluge: Unable to send Torrent

**Comment by eschultz** [comment]
Are you sure this is a issue with Plex?  

This sounds like a issue with SickRage/Sickbeard talking to Deluge if i'm reading your log entry correctly but this repo is only for the Plex container.  We don't have a official SickRage or Deluge container so I might be confused on how you have everything setup on your side.

**Comment by scbuckeye75** [comment]
So sorry!  I posted in the wrong repository!  I will move this to the correct forum.
